In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Data exploration

In [4]:
df_enron = pd.read_csv('./data/Enron.csv')
df_ling = pd.read_csv('./data/Ling.csv')
df_nazario = pd.read_csv('./data/Nazario.csv')
df_nigerian = pd.read_csv('./data/Nigerian_Fraud.csv')
df_phishing = pd.read_csv('./data/Phishing_email.csv')
df_spamAssassin = pd.read_csv('./data/SpamAssasin.csv')

In [5]:
df_enron.head(10)

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0
5,hpl nom for may 31 2001,( see attached file : hplno 531 . xls )\r\n- h...,0
6,# 9760,tried to get fancy with your address and it ca...,0
7,"hpl noms for february 15 , 2000",( see attached file : hplo 215 . xls )\r\n- hp...,0
8,fw : pooling contract template,- - - - - original message - - - - -\r\nfrom :...,0
9,"hpl nom for march 28 , 2000",( see attached file : hplo 328 . xls )\r\n- hp...,0

In [6]:
df_ling.head(10)

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0
5,call for abstracts : optimality in syntactic t...,content - length : 4437 call for papers is the...,0
6,m . a . in scandinavian linguistics,m . a . in scandinavian linguistics at the uni...,0
7,call for papers : linguistics session of the m...,call for papers linguistics session - - midwes...,0
8,foreign language in commercials,content - length : 1937 greetings ! i ' m wond...,0
9,fulbright announcement : please post / dissemi...,fulbright announcement : please post / dissemi...,0

In [7]:
df_nazario.head(10)

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1
5,=?utf-8?Q?P=2eSupport?= <infos@2015p.com>,jose@monkey.org,"Sat, 31 Oct 2015 13:38:13 +0000",=?utf-8?Q?Dear=20Client=20=3a=20Update=20Your=...,"PayPal Secure Dear Client, ...",1,1
6,Update,Recipients,"Sat, 31 Oct 2015 20:44:17 +0530",Update,08/10/2011 06:14:36 am +0800 - en_US.UTF-8 - O...,1,1
7,"""USAA"" <usaa-offers@banking2.org>",Recipients <usaa-offers@banking2.org>,"Tue, 03 Nov 2015 22:18:36 +1300",IMPORTANT NEW MESSAGE FROM USAA,E-mail Address Update\t View Accounts | Pri...,1,1
8,"""Tourne, Michele"" <MTourne@co.humboldt.ca.us>",Undisclosed recipients:;,"Mon, 2 Nov 2015 12:59:51 +0000",Mailbox Warning!!!,"Dear Valued User, We are having a majo...",1,1
9,"""English, Saundra (FDNY)"" <Saundra.English@fdn...","""info@eeee.org"" <info@eeee.org>","Tue, 3 Nov 2015 16:27:37 -0500",Help Desk Password Update,Password will expire in 3 days. Click Here To ...,1,1

In [8]:
df_nigerian.head(10)

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1
5,Kuta David <davidkuta@postmark.net>,davidkuta@yahoo.com,"Sat, 02 Nov 2002 06:23:11 +0000",Partnership,ATTENTION: ...,0,1
6,Barrister tunde dosumu <tunde_dosumu@lycos.com>,NaN,NaN,Urgent Attention,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1
7,William Drallo <william2244drallo@maktoob.com>,webmaster@aclweb.org,"Sun, 03 Nov 2002 23:56:20 +0000",URGENT BUSINESS PRPOSAL,FROM: WILLIAM DRALLO.\nCONFIDENTIAL TEL: 233-2...,0,1
8,MR USMAN ABDUL <abdul_817@rediffmail.com>,R@M,"Mon, 04 Nov 2002 23:41:26 -0000",THANK YOU,"CHALLENGE SECURITIES LTD.\nLAGOS, NIGERIA\n\n\...",0,1
9,Tunde Dosumu <barrister_td@lycos.com>,NaN,NaN,Urgent Assistance,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1

In [10]:
df_spamAssassin.head(10)

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1
5,"""Martin Adamson"" <martin@srv0.ems.ed.ac.uk>",zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:50:31 +0100",Re: [zzzzteana] Nothing like mama used to make,> I just had to jump in here as Carbonara is o...,0,1
6,"""Martin Adamson"" <martin@srv0.ems.ed.ac.uk>",zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:54:25 +0100",[zzzzteana] Playboy wants to go out with a bang,The Scotsman - 22 August 2002\n\n Playboy want...,0,1
7,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 15:01:20 +0100",Re: [zzzzteana] Nothing like mama used to make,Martin Adamson wrote: > > Isn't it just basic...,0,1
8,"""Martin Adamson"" <martin@srv0.ems.ed.ac.uk>",zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 15:01:33 +0100",[zzzzteana] Meaningful sentences,The Scotsman\n\n Thu 22 Aug 2002 \n\n Meaningf...,0,1
9,"""NOI Administrator"" <admin@networksonline.com>",<spamassassin-talk@example.sourceforge.net>,"Thu, 22 Aug 2002 10:16:36 -0400",[SAtalk] SA CGI Configurator Scripts,I have been trying to research via SA mirrors ...,0,1