In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Data exploration

In [4]:
df_enron = pd.read_csv('./data/Enron.csv')
df_ling = pd.read_csv('./data/Ling.csv')
df_nazario = pd.read_csv('./data/Nazario.csv')
df_nigerian = pd.read_csv('./data/Nigerian_Fraud.csv')
df_phishing = pd.read_csv('./data/Phishing_email.csv')
df_spamAssassin = pd.read_csv('./data/SpamAssasin.csv')

In [5]:
df_enron.head(10)

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0
5,hpl nom for may 31 2001,( see attached file : hplno 531 . xls )\r\n- h...,0
6,# 9760,tried to get fancy with your address and it ca...,0
7,"hpl noms for february 15 , 2000",( see attached file : hplo 215 . xls )\r\n- hp...,0
8,fw : pooling contract template,- - - - - original message - - - - -\r\nfrom :...,0
9,"hpl nom for march 28 , 2000",( see attached file : hplo 328 . xls )\r\n- hp...,0

In [6]:
df_ling.head(10)

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0
5,call for abstracts : optimality in syntactic t...,content - length : 4437 call for papers is the...,0
6,m . a . in scandinavian linguistics,m . a . in scandinavian linguistics at the uni...,0
7,call for papers : linguistics session of the m...,call for papers linguistics session - - midwes...,0
8,foreign language in commercials,content - length : 1937 greetings ! i ' m wond...,0
9,fulbright announcement : please post / dissemi...,fulbright announcement : please post / dissemi...,0

In [7]:
df_nazario.head(10)

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1
5,=?utf-8?Q?P=2eSupport?= <infos@2015p.com>,jose@monkey.org,"Sat, 31 Oct 2015 13:38:13 +0000",=?utf-8?Q?Dear=20Client=20=3a=20Update=20Your=...,"PayPal Secure Dear Client, ...",1,1
6,Update,Recipients,"Sat, 31 Oct 2015 20:44:17 +0530",Update,08/10/2011 06:14:36 am +0800 - en_US.UTF-8 - O...,1,1
7,"""USAA"" <usaa-offers@banking2.org>",Recipients <usaa-offers@banking2.org>,"Tue, 03 Nov 2015 22:18:36 +1300",IMPORTANT NEW MESSAGE FROM USAA,E-mail Address Update\t View Accounts | Pri...,1,1
8,"""Tourne, Michele"" <MTourne@co.humboldt.ca.us>",Undisclosed recipients:;,"Mon, 2 Nov 2015 12:59:51 +0000",Mailbox Warning!!!,"Dear Valued User, We are having a majo...",1,1
9,"""English, Saundra (FDNY)"" <Saundra.English@fdn...","""info@eeee.org"" <info@eeee.org>","Tue, 3 Nov 2015 16:27:37 -0500",Help Desk Password Update,Password will expire in 3 days. Click Here To ...,1,1

In [8]:
df_nigerian.head(10)

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1
5,Kuta David <davidkuta@postmark.net>,davidkuta@yahoo.com,"Sat, 02 Nov 2002 06:23:11 +0000",Partnership,ATTENTION: ...,0,1
6,Barrister tunde dosumu <tunde_dosumu@lycos.com>,NaN,NaN,Urgent Attention,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1
7,William Drallo <william2244drallo@maktoob.com>,webmaster@aclweb.org,"Sun, 03 Nov 2002 23:56:20 +0000",URGENT BUSINESS PRPOSAL,FROM: WILLIAM DRALLO.\nCONFIDENTIAL TEL: 233-2...,0,1
8,MR USMAN ABDUL <abdul_817@rediffmail.com>,R@M,"Mon, 04 Nov 2002 23:41:26 -0000",THANK YOU,"CHALLENGE SECURITIES LTD.\nLAGOS, NIGERIA\n\n\...",0,1
9,Tunde Dosumu <barrister_td@lycos.com>,NaN,NaN,Urgent Assistance,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1

In [10]:
df_spamAssassin.head(10)

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1
5,"""Martin Adamson"" <martin@srv0.ems.ed.ac.uk>",zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:50:31 +0100",Re: [zzzzteana] Nothing like mama used to make,> I just had to jump in here as Carbonara is o...,0,1
6,"""Martin Adamson"" <martin@srv0.ems.ed.ac.uk>",zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:54:25 +0100",[zzzzteana] Playboy wants to go out with a bang,The Scotsman - 22 August 2002\n\n Playboy want...,0,1
7,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 15:01:20 +0100",Re: [zzzzteana] Nothing like mama used to make,Martin Adamson wrote: > > Isn't it just basic...,0,1
8,"""Martin Adamson"" <martin@srv0.ems.ed.ac.uk>",zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 15:01:33 +0100",[zzzzteana] Meaningful sentences,The Scotsman\n\n Thu 22 Aug 2002 \n\n Meaningf...,0,1
9,"""NOI Administrator"" <admin@networksonline.com>",<spamassassin-talk@example.sourceforge.net>,"Thu, 22 Aug 2002 10:16:36 -0400",[SAtalk] SA CGI Configurator Scripts,I have been trying to research via SA mirrors ...,0,1

## Phase 1: Deep EDA — Understanding the Data

Before building ANY model, we need to deeply understand what we're working with. This phase answers critical questions:

- **How many emails** are in each dataset? What columns do they have?
- **Are there missing values?** Where and how many?
- **Is the data balanced?** Equal phishing vs. legitimate? (Critical — imbalanced data breaks naive accuracy metrics)
- **Do phishing emails differ in length** from legitimate ones? (Length itself can be a feature)

### Why this matters
Every assumption made here propagates through the entire pipeline. If you miss a null-handling issue now, your model will silently fail later. If you don't check class balance, you might train a model with "95% accuracy" that never actually catches a single phishing email.

In [ ]:
# 1.1 — Shape and column overview for every dataset
# This tells us: how large is each dataset, and do the schemas match?

datasets = {
    'Enron': df_enron,
    'Ling': df_ling,
    'Nazario': df_nazario,
    'Nigerian_Fraud': df_nigerian,
    'SpamAssassin': df_spamAssassin,
}

print("=" * 60)
for name, df in datasets.items():
    print(f"\n{'='*20} {name} {'='*20}")
    print(f"  Shape     : {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"  Columns   : {list(df.columns)}")
    print(f"  Label val : {df['label'].unique()}")
print("=" * 60)
print(f"\nTotal rows across all datasets: {sum(df.shape[0] for df in datasets.values()):,}")

### 1.2 — Missing Values Analysis

Null values are dangerous in text ML:
- A null **`body`** means we have NO content to analyze — that row must be **dropped**
- A null **`subject`** is totally normal (many legitimate emails have no subject) — fill with `""`
- Null `sender`, `receiver`, `date` are acceptable — we won't use those as final features

The heatmap below makes null patterns visually obvious. Yellow = null, dark = present.

In [ ]:
# 1.2 — Null value counts and heatmaps
fig, axes = plt.subplots(1, 5, figsize=(22, 5))
fig.suptitle("Missing Values per Dataset (yellow = null)", fontsize=14, fontweight='bold')

for ax, (name, df) in zip(axes, datasets.items()):
    # msno-style heatmap using seaborn
    null_matrix = df.isnull().astype(int)
    sns.heatmap(null_matrix, ax=ax, cbar=False, yticklabels=False,
                cmap='YlOrRd', vmin=0, vmax=1)
    ax.set_title(f"{name}\n({df.shape[0]:,} rows)", fontsize=10)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', fontsize=8)

plt.tight_layout()
plt.show()

# Summary table
print("\n=== NULL COUNTS PER DATASET ===")
for name, df in datasets.items():
    nulls = df.isnull().sum()
    if nulls.sum() > 0:
        print(f"\n{name}:")
        print(nulls[nulls > 0].to_string())
    else:
        print(f"\n{name}: No nulls")

### 1.3 — Label Distribution: Are We Dealing with Class Imbalance?

**This is the most important single check in fraud/phishing detection.**

Imagine a dataset that's 90% legitimate emails. A model that *always* predicts "legitimate" gets 90% accuracy — and is completely useless. This is why **accuracy is a bad primary metric** for phishing detection. Instead we'll use F1-score and Recall.

The chart below shows how many phishing (label=1) vs. legitimate (label=0) emails are in each dataset and in total.

In [ ]:
# 1.3 — Label distribution per dataset + combined
fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()
label_names = {0: 'Legitimate', 1: 'Phishing/Fraud'}
colors = ['#2ecc71', '#e74c3c']

combined_counts = {0: 0, 1: 0}

for i, (name, df) in enumerate(datasets.items()):
    counts = df['label'].value_counts().sort_index()
    for lbl, cnt in counts.items():
        combined_counts[lbl] = combined_counts.get(lbl, 0) + cnt
    bars = axes[i].bar(
        [label_names.get(l, str(l)) for l in counts.index],
        counts.values,
        color=[colors[l] for l in counts.index]
    )
    axes[i].set_title(f"{name}", fontweight='bold')
    axes[i].set_ylabel("Count")
    for bar, val in zip(bars, counts.values):
        axes[i].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 10,
                     f'{val:,}', ha='center', va='bottom', fontsize=10)

# Combined plot
combined_series = pd.Series(combined_counts)
bars = axes[5].bar(
    [label_names[l] for l in combined_series.index],
    combined_series.values,
    color=colors
)
axes[5].set_title("COMBINED (All Datasets)", fontweight='bold')
axes[5].set_ylabel("Count")
for bar, val in zip(bars, combined_series.values):
    axes[5].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50,
                 f'{val:,}', ha='center', va='bottom', fontsize=10)
total = sum(combined_counts.values())
ratio = combined_counts[0] / combined_counts.get(1, 1)
axes[5].set_xlabel(f"Imbalance ratio ≈ {ratio:.1f}:1 (legit:phishing)", fontsize=10)

plt.suptitle("Label Distribution per Dataset", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print(f"\n{'='*40}")
print(f"COMBINED: {combined_counts[0]:,} legitimate | {combined_counts.get(1, 0):,} phishing")
print(f"Imbalance ratio: {ratio:.2f}:1")

### 1.4 — Text Length Distributions by Label

Phishing emails tend to follow certain length patterns:
- **Short subjects** with high-impact words ("URGENT", "Verify Your Account")
- **Bodies** that can be very short (one-liners) or very long (filled with fake HTML formatting)

By plotting length distributions separately for each label, we can confirm whether length is a useful signal — and if so, it becomes a feature in our model.

> **Reading the violin plot**: The width shows how many emails have that length. A wide middle means most emails are that length. The inner white dot is the median.

In [ ]:
# 1.4 — Text length distributions split by label
# We need a combined dataframe for this (just subject + body + label)
df_len = pd.concat([
    df[['subject', 'body', 'label']].copy() for df in datasets.values()
], ignore_index=True)

df_len['subject'] = df_len['subject'].fillna('')
df_len['body'] = df_len['body'].fillna('')
df_len['subject_len'] = df_len['subject'].str.len()
df_len['body_len'] = df_len['body'].str.len()
df_len['label_name'] = df_len['label'].map({0: 'Legitimate', 1: 'Phishing'})

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Subject length — cap outliers for readability
cap_subj = df_len['subject_len'].quantile(0.98)
sns.violinplot(
    data=df_len[df_len['subject_len'] <= cap_subj],
    x='label_name', y='subject_len', ax=axes[0],
    palette={'Legitimate': '#2ecc71', 'Phishing': '#e74c3c'},
    inner='box', cut=0
)
axes[0].set_title("Subject Length by Label (capped at 98th pct)", fontweight='bold')
axes[0].set_xlabel("Label")
axes[0].set_ylabel("Characters")

# Body length — log scale because distribution is very wide
cap_body = df_len['body_len'].quantile(0.95)
plot_df = df_len[df_len['body_len'] <= cap_body].copy()
sns.violinplot(
    data=plot_df,
    x='label_name', y='body_len', ax=axes[1],
    palette={'Legitimate': '#2ecc71', 'Phishing': '#e74c3c'},
    inner='box', cut=0
)
axes[1].set_title("Body Length by Label (capped at 95th pct)", fontweight='bold')
axes[1].set_xlabel("Label")
axes[1].set_ylabel("Characters")

plt.suptitle("Text Length Distributions: Phishing vs. Legitimate", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Numeric summary
print("\n=== MEDIAN TEXT LENGTHS ===")
summary = df_len.groupby('label_name')[['subject_len', 'body_len']].median()
print(summary.to_string())

## Phase 2: Data Cleaning & Schema Unification

Our 5 datasets have **inconsistent schemas** — some have `sender/receiver/date/urls`, others only have `subject/body/label`. We need to create one unified DataFrame before any ML work.

### Strategy
1. **Extract `has_url`** from the `urls` column (for datasets that have it) as a binary feature (0/1), then drop the column
2. **Drop metadata columns** (`sender`, `receiver`, `date`) — they're not available in all datasets and carry privacy risk
3. **Keep only**: `subject`, `body`, `label`, `has_url`
4. **Concatenate** all 5 DataFrames
5. **Handle nulls**: fill null subjects with `""`, drop rows with null body (no content = no signal)
6. **Drop duplicates** — some phishing emails appear in multiple datasets

### Why drop sender/date even though they have signal?
In a real phishing detector, you might have sender info. But for a **generalizable model** trained on mixed datasets, sender addresses are dataset-specific artifacts, not patterns. If Nazario phishing emails all come from certain domains, the model learns those specific domains instead of the email *content* — making it brittle on new data.

In [ ]:
# 2.1 — Extract has_url flag and normalize schemas

def extract_has_url(df):
    """Convert the urls column to a binary has_url flag."""
    if 'urls' in df.columns:
        # urls column contains integers (0 or 1) indicating URL presence
        return df['urls'].apply(lambda x: 1 if pd.notna(x) and str(x).strip() not in ('0', '', 'nan') else 0)
    else:
        return pd.Series(0, index=df.index)  # conservative: assume no URL info

# Build normalized copies of each dataset
dfs_normalized = []
for name, df in datasets.items():
    df_norm = pd.DataFrame({
        'subject': df['subject'],
        'body': df['body'],
        'label': df['label'],
        'has_url': extract_has_url(df),
        'source': name  # keep track of origin for debugging
    })
    dfs_normalized.append(df_norm)
    print(f"{name}: {len(df_norm):,} rows → has_url distribution: {df_norm['has_url'].value_counts().to_dict()}")

# 2.2 — Concatenate
df_all = pd.concat(dfs_normalized, ignore_index=True)
print(f"\nCombined shape: {df_all.shape}")
print(f"Label distribution:\n{df_all['label'].value_counts().to_string()}")

In [ ]:
# 2.3 — Handle nulls and duplicates

print(f"Before cleaning: {len(df_all):,} rows")
print(f"  Null subjects : {df_all['subject'].isnull().sum():,}")
print(f"  Null bodies   : {df_all['body'].isnull().sum():,}")

# Fill null subjects (normal — many emails have no subject)
df_all['subject'] = df_all['subject'].fillna('')

# Drop rows with null body (no text = no signal)
df_all = df_all.dropna(subset=['body'])
print(f"\nAfter dropping null bodies: {len(df_all):,} rows")

# Drop exact duplicates (same subject + body = same email)
df_all = df_all.drop_duplicates(subset=['subject', 'body'])
print(f"After deduplication: {len(df_all):,} rows")

# Reset index
df_all = df_all.reset_index(drop=True)

print(f"\nFinal label distribution:")
counts = df_all['label'].value_counts().sort_index()
for lbl, cnt in counts.items():
    name = 'Legitimate' if lbl == 0 else 'Phishing'
    pct = cnt / len(df_all) * 100
    print(f"  {name} (label={lbl}): {cnt:,} ({pct:.1f}%)")

print(f"\nFinal dataset shape: {df_all.shape}")
df_all.head(3)

## Phase 3: Text Preprocessing

Raw email text is extremely noisy. Before we can extract meaningful features or build vocabulary vectors, we need to **standardize the text**. Here's what we clean and why:

| Step | What | Why |
|------|------|-----|
| Lowercase | `"VERIFY YOUR ACCOUNT"` → `"verify your account"` | Same word shouldn't count as two different tokens |
| Remove HTML tags | `<a href="...">Click</a>` → `"Click"` | Email bodies often contain HTML; tags add noise |
| Extract URL flag | Count URLs before removing them | URLs are a strong phishing signal — we capture this as a feature |
| Replace URLs | Replace all URLs with the token `"URL"` | Keeps the *presence* of URLs as a signal without overfitting to specific domains |
| Remove special characters | Keep only letters, digits, spaces | Punctuation like `!!!` creates vocabulary noise |
| Collapse whitespace | `"  hello   world  "` → `"hello world"` | Inconsistent spacing from HTML stripping |

### Why NOT remove stopwords?
In general NLP, stopwords ("the", "is", "you") are removed. But for phishing, words like **"your"**, **"you"**, **"immediately"** carry strong signal. We'll keep them.

### Combining subject + body
The subject line is disproportionately important in phishing — it's crafted to trick the user into opening the email. By prepending the subject to the body, we give it more weight in the vocabulary.

In [ ]:
import re

def preprocess_text(text):
    """
    Clean a single email text string.
    Steps: lowercase → remove HTML → replace URLs → remove special chars → collapse whitespace
    """
    if not isinstance(text, str):
        return ""
    # 1. Lowercase
    text = text.lower()
    # 2. Remove HTML tags
    text = re.sub(r'<[^>]+>', ' ', text)
    # 3. Replace URLs with a token (presence is captured separately as has_url)
    text = re.sub(r'https?://\S+|www\.\S+', ' url ', text)
    # 4. Remove non-alphanumeric characters (keep spaces and letters/digits)
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    # 5. Collapse multiple whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Apply preprocessing
print("Preprocessing text... (may take ~1-2 minutes for large datasets)")
df_all['subject_clean'] = df_all['subject'].apply(preprocess_text)
df_all['body_clean'] = df_all['body'].apply(preprocess_text)

# Combine: subject prepended to body (subject gets proportionally more weight)
# We repeat subject twice to amplify its influence — a deliberate design choice
df_all['email_text'] = df_all['subject_clean'] + ' ' + df_all['subject_clean'] + ' ' + df_all['body_clean']

print("Done! Sample cleaned emails:")
print("\n--- PHISHING EXAMPLE ---")
phishing_sample = df_all[df_all['label'] == 1].iloc[0]
print(f"Subject (clean): {phishing_sample['subject_clean'][:100]}")
print(f"Body (clean):    {phishing_sample['body_clean'][:200]}")

print("\n--- LEGITIMATE EXAMPLE ---")
legit_sample = df_all[df_all['label'] == 0].iloc[0]
print(f"Subject (clean): {legit_sample['subject_clean'][:100]}")
print(f"Body (clean):    {legit_sample['body_clean'][:200]}")

## Phase 4: Feature Engineering

This is where domain knowledge about phishing becomes **competitive advantage**. Instead of just feeding raw text to a model (which only works well for deep learning), we engineer explicit numeric features that capture known phishing patterns.

We build **two types of features** that we'll combine:

### Type A: Handcrafted features (numeric, fast, interpretable)
Based on what we know phishing emails look like:
- They use **urgency language** ("verify", "account suspended", "act now")
- They're **full of capital letters** and exclamation marks for emphasis
- They reference **account/financial information** with lots of digits
- Short or repetitive text (Nigerian fraud style)

### Type B: TF-IDF text features (statistical, vocabulary-based)
**TF-IDF** (Term Frequency–Inverse Document Frequency) converts text into a numeric vector. For each word:
- **TF** = how often the word appears in THIS email
- **IDF** = how rare the word is across ALL emails

Result: common words (like "the") get low weight; rare, distinctive words (like "usaa", "password-expired") get high weight. We use **bigrams** (two-word phrases) too, so "verify account" is captured as a unit, not just "verify" and "account" separately.

### Combining both types
We use `scipy.sparse.hstack` to horizontally stack:
- The TF-IDF sparse matrix (5000 columns, most are zero for any given email)
- The dense numeric features (a few columns, all non-zero)

This gives each model access to both vocabulary patterns AND structural signals.

In [ ]:
# 4.1 — Handcrafted phishing-signal features (computed on RAW text, before cleaning)

# Urgency keywords — words deliberately used to create panic and prompt action
URGENCY_KEYWORDS = [
    'verify', 'update', 'confirm', 'urgent', 'immediately', 'suspend',
    'account', 'password', 'click', 'login', 'security', 'limited',
    'act now', 'expire', 'validate', 'reactivate', 'locked', 'blocked',
    'alert', 'attention', 'warning', 'important', 'unusual activity'
]

def compute_features(row):
    raw_text = str(row['subject']) + ' ' + str(row['body'])
    raw_lower = raw_text.lower()
    
    # Subject length
    subj_len = len(str(row['subject']))
    
    # Body length
    body_len = len(str(row['body']))
    
    # Word count (from cleaned text)
    word_count = len(str(row['email_text']).split())
    
    # Urgency score: count how many urgency keywords appear
    urgency_score = sum(1 for kw in URGENCY_KEYWORDS if kw in raw_lower)
    
    # Caps ratio: proportion of uppercase letters (phishing loves SHOUTING)
    letters = [c for c in raw_text if c.isalpha()]
    caps_ratio = sum(1 for c in letters if c.isupper()) / (len(letters) + 1)
    
    # Exclamation count
    exclamation_count = raw_text.count('!')
    
    # Digit ratio (fraud emails reference lots of account numbers/amounts)
    digit_ratio = sum(1 for c in raw_text if c.isdigit()) / (len(raw_text) + 1)
    
    # Unique word ratio: low uniqueness = repetitive/template text
    words = raw_lower.split()
    unique_word_ratio = len(set(words)) / (len(words) + 1)
    
    return pd.Series({
        'subject_len': subj_len,
        'body_len': body_len,
        'word_count': word_count,
        'urgency_score': urgency_score,
        'caps_ratio': caps_ratio,
        'exclamation_count': exclamation_count,
        'digit_ratio': digit_ratio,
        'unique_word_ratio': unique_word_ratio,
    })

print("Computing handcrafted features... (may take a moment)")
features_df = df_all.apply(compute_features, axis=1)
df_all = pd.concat([df_all, features_df], axis=1)

print("Done! Feature statistics by label:")
feature_cols = list(features_df.columns) + ['has_url']
print(df_all.groupby('label')[feature_cols].mean().round(3).to_string())

In [ ]:
# 4.2 — Visualize feature distributions: Do our engineered features separate the classes?
# This is the validation step — if a feature doesn't separate classes, it adds noise.

fig, axes = plt.subplots(2, 4, figsize=(20, 9))
axes = axes.flatten()

plot_features = ['urgency_score', 'caps_ratio', 'exclamation_count',
                 'digit_ratio', 'unique_word_ratio', 'has_url',
                 'subject_len', 'body_len']

for ax, feat in zip(axes, plot_features):
    for label, color, name in [(0, '#2ecc71', 'Legitimate'), (1, '#e74c3c', 'Phishing')]:
        subset = df_all[df_all['label'] == label][feat]
        # Cap at 99th percentile for readability
        cap = subset.quantile(0.99)
        subset_capped = subset[subset <= cap]
        ax.hist(subset_capped, bins=40, alpha=0.6, color=color, label=name, density=True)
    ax.set_title(feat, fontweight='bold')
    ax.legend(fontsize=8)
    ax.set_ylabel("Density")

plt.suptitle("Feature Distributions: Phishing vs. Legitimate\n(Separation = useful feature)", 
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import scipy.sparse as sp
from sklearn.preprocessing import StandardScaler

# 4.3 — TF-IDF vectorization
# max_features=5000: keep only the 5000 most informative words/bigrams
# ngram_range=(1,2): use both unigrams ("verify") and bigrams ("verify account")
# min_df=2: ignore words that appear in fewer than 2 documents (likely typos/noise)
# sublinear_tf=True: use log(1+tf) instead of raw tf — dampens effect of very frequent words

print("Fitting TF-IDF vectorizer...")
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)
X_tfidf = tfidf.fit_transform(df_all['email_text'])
print(f"TF-IDF matrix shape: {X_tfidf.shape}")
print(f"  → {X_tfidf.shape[0]:,} emails × {X_tfidf.shape[1]:,} word/bigram features")
print(f"  → Sparsity: {(1 - X_tfidf.nnz / (X_tfidf.shape[0] * X_tfidf.shape[1])):.1%} of values are zero")

# 4.4 — Combine TF-IDF with handcrafted features
HANDCRAFTED_COLS = ['subject_len', 'body_len', 'word_count', 'urgency_score',
                     'caps_ratio', 'exclamation_count', 'digit_ratio', 
                     'unique_word_ratio', 'has_url']

# Scale numeric features to [0,1] range so they don't dominate TF-IDF
scaler = StandardScaler()
X_numeric = scaler.fit_transform(df_all[HANDCRAFTED_COLS])
X_numeric_sparse = sp.csr_matrix(X_numeric)

# Stack horizontally: each row = one email, columns = TF-IDF + numeric features
X = sp.hstack([X_tfidf, X_numeric_sparse])
y = df_all['label'].values

print(f"\nFinal feature matrix shape: {X.shape}")
print(f"  → {X.shape[1]} total features ({X_tfidf.shape[1]} TF-IDF + {len(HANDCRAFTED_COLS)} handcrafted)")
print(f"\nTop 20 most informative TF-IDF features by IDF weight:")
feature_names = tfidf.get_feature_names_out()
idf_scores = tfidf.idf_
top_idx = idf_scores.argsort()[-20:][::-1]
for idx in top_idx:
    print(f"  '{feature_names[idx]}': {idf_scores[idx]:.3f}")

## Phase 5: Class Imbalance & Train/Test Split

### Why imbalance is dangerous

Suppose we have 80,000 legitimate emails and 20,000 phishing emails (4:1 ratio). A model that **always predicts "legitimate"** achieves **80% accuracy** with zero actual usefulness. This is why we need special handling.

### Our approach: `class_weight='balanced'`
Most sklearn models accept a `class_weight='balanced'` parameter. This makes the model internally penalize mistakes on the minority class more heavily — equivalent to oversampling phishing emails during training, but without actually duplicating data.

**Formula**: weight for class `i` = `total_samples / (n_classes × count_of_class_i)`

### Train/Test split: why `stratify=y`?
Without stratification, random splitting could put all phishing emails in train and none in test (by chance, especially if phishing is rare). `stratify=y` guarantees both splits have the same class ratio.

In [ ]:
from sklearn.model_selection import train_test_split

# 5.1 — Check class imbalance ratio
class_counts = pd.Series(y).value_counts().sort_index()
n_legit = class_counts.get(0, 0)
n_phish = class_counts.get(1, 0)
imbalance_ratio = n_legit / n_phish if n_phish > 0 else float('inf')

print(f"Class distribution:")
print(f"  Legitimate (0): {n_legit:,} ({n_legit/len(y)*100:.1f}%)")
print(f"  Phishing   (1): {n_phish:,} ({n_phish/len(y)*100:.1f}%)")
print(f"  Imbalance ratio: {imbalance_ratio:.2f}:1")

if imbalance_ratio > 3:
    print(f"\n⚠️  Significant imbalance detected ({imbalance_ratio:.1f}:1).")
    print("   We'll use class_weight='balanced' in all models.")
else:
    print(f"\n✓ Imbalance is manageable ({imbalance_ratio:.1f}:1).")

# XGBoost's equivalent of class_weight='balanced'
xgb_scale_pos_weight = n_legit / n_phish
print(f"\nXGBoost scale_pos_weight = {xgb_scale_pos_weight:.2f}")

# 5.2 — Stratified train/test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y  # ensures same class ratio in both splits
)

print(f"\nTrain set: {X_train.shape[0]:,} samples")
print(f"  Legitimate: {(y_train == 0).sum():,} | Phishing: {(y_train == 1).sum():,}")
print(f"\nTest set: {X_test.shape[0]:,} samples")
print(f"  Legitimate: {(y_test == 0).sum():,} | Phishing: {(y_test == 1).sum():,}")

## Phase 7: Model Training

We train 3 models, chosen deliberately to represent different algorithmic approaches:

### Model 1: Logistic Regression
**What it does**: Learns a linear decision boundary — it finds a weighted sum of features that best separates phishing from legitimate. Think of it as learning: "if urgency_score > X AND has the word 'verify' → phishing".

**Why start here**: It's the best baseline for text classification with TF-IDF. Fast, interpretable (you can look at the coefficients to understand what drives predictions), and often surprisingly competitive.

**Key parameters**:
- `C=1.0`: Regularization strength — higher C = less regularization = model can fit training data more closely (risk of overfitting)
- `class_weight='balanced'`: compensates for imbalance
- `max_iter=1000`: LR uses iterative optimization; needs enough iterations to converge

---

### Model 2: Random Forest
**What it does**: Trains 200 decision trees, each on a random subset of data and features. The final prediction is a majority vote across all trees. This "ensemble" approach is much more robust than a single tree.

**Why include it**: Random Forest naturally handles **non-linear relationships** (unlike LR). It also provides **feature importance** scores, which will help us understand which signals matter most.

**Key parameters**:
- `n_estimators=200`: 200 trees. More = better but slower
- `max_depth=20`: Prevents trees from memorizing training data
- `class_weight='balanced'`

---

### Model 3: Gradient Boosting (XGBoost)
**What it does**: Trains trees **sequentially** — each new tree corrects the errors of the previous ones. This "boosting" process often yields the best performance on structured/tabular problems.

**Why include it**: XGBoost is consistently the top performer in ML competitions on structured data. It handles the interaction between our handcrafted features and TF-IDF particularly well.

**Key parameters**:
- `scale_pos_weight`: equivalent to `class_weight='balanced'` for XGBoost
- `n_estimators=200, max_depth=6`: balanced speed/accuracy
- `learning_rate=0.1`: how much each tree contributes — smaller = more conservative, usually better

In [ ]:
import time
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

# Try importing XGBoost; fall back to GradientBoostingClassifier if not installed
try:
    from xgboost import XGBClassifier
    xgb_available = True
    print("XGBoost available.")
except ImportError:
    from sklearn.ensemble import GradientBoostingClassifier
    xgb_available = False
    print("XGBoost not found — using sklearn GradientBoostingClassifier instead.")
    print("To install: pip install xgboost")

# === MODEL 1: Logistic Regression ===
print("\n" + "="*50)
print("Training Model 1: Logistic Regression...")
t0 = time.time()
lr = LogisticRegression(
    C=1.0,
    class_weight='balanced',
    max_iter=1000,
    solver='lbfgs',
    random_state=42
)
lr.fit(X_train, y_train)
print(f"  Done in {time.time()-t0:.1f}s")

# === MODEL 2: Random Forest ===
print("\nTraining Model 2: Random Forest (200 trees)...")
t0 = time.time()
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1  # use all CPU cores
)
rf.fit(X_train, y_train)
print(f"  Done in {time.time()-t0:.1f}s")

# === MODEL 3: XGBoost / Gradient Boosting ===
print("\nTraining Model 3: Gradient Boosting...")
t0 = time.time()
if xgb_available:
    gb = XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        scale_pos_weight=xgb_scale_pos_weight,
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    )
else:
    gb = GradientBoostingClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        random_state=42
    )
gb.fit(X_train, y_train)
print(f"  Done in {time.time()-t0:.1f}s")

print("\nAll 3 models trained successfully!")

## Phase 8: Evaluation & Comparison

### Understanding the metrics

For phishing detection, metrics have very concrete meaning:

| Metric | Formula | Meaning in our context |
|--------|---------|----------------------|
| **Recall** | TP / (TP + FN) | Of all actual phishing emails, what % did we catch? **Missed phishing = user gets harmed** |
| **Precision** | TP / (TP + FP) | Of all emails we flagged as phishing, what % really were? Too low = users ignore alerts (cry wolf) |
| **F1-score** | 2 × (P×R)/(P+R) | Harmonic mean — the right single metric when recall and precision both matter |
| **ROC-AUC** | Area under ROC curve | Model's overall discrimination ability (threshold-independent) |
| **Accuracy** | (TP+TN)/(all) | Least useful here — misleading with imbalanced data |

### The recall vs. precision tradeoff
In security, **recall is usually more important** — better to flag a few extra suspicious emails (false alarms are annoying) than to miss actual phishing (user gets hacked). However, if false alarm rate is too high, users start ignoring ALL alerts, making the system useless. We need to find the right balance.

In [ ]:
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score,
    roc_curve, precision_recall_curve, average_precision_score, accuracy_score
)

models = {
    'Logistic Regression': lr,
    'Random Forest': rf,
    'Gradient Boosting': gb,
}

# Collect predictions and probabilities for all models
results = {}
for name, model in models.items():
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]  # probability of being phishing
    results[name] = {'y_pred': y_pred, 'y_proba': y_proba}

# 8.1 — Classification reports (precision, recall, F1 per class)
print("=" * 65)
for name, res in results.items():
    print(f"\n{'='*65}")
    print(f"  {name}")
    print(f"{'='*65}")
    print(classification_report(y_test, res['y_pred'],
                                target_names=['Legitimate', 'Phishing']))

In [ ]:
# 8.2 — Confusion matrices: visualize what kinds of errors each model makes

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
class_labels = ['Legitimate', 'Phishing']

for ax, (name, res) in zip(axes, results.items()):
    cm = confusion_matrix(y_test, res['y_pred'])
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=class_labels, yticklabels=class_labels,
                annot_kws={'size': 14})
    ax.set_title(f"{name}", fontweight='bold')
    ax.set_ylabel("Actual")
    ax.set_xlabel("Predicted")
    
    # Add interpretation below each matrix
    tn, fp, fn, tp = cm.ravel()
    missed = fn / (tp + fn) * 100 if (tp + fn) > 0 else 0
    false_alarm = fp / (tn + fp) * 100 if (tn + fp) > 0 else 0
    ax.set_xlabel(
        f"Predicted\n[Missed phishing: {missed:.1f}% | False alarms: {false_alarm:.1f}%]"
    )

plt.suptitle("Confusion Matrices\n(Missed phishing = dangerous | False alarms = annoying)", 
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

In [ ]:
# 8.3 — ROC Curves + Precision-Recall Curves (all 3 models overlaid)
# ROC curve: plots True Positive Rate vs False Positive Rate at every threshold
# PR curve: plots Precision vs Recall at every threshold (better for imbalanced data)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
colors_models = ['#3498db', '#e67e22', '#9b59b6']

for (name, res), color in zip(results.items(), colors_models):
    y_proba = res['y_proba']
    
    # ROC curve
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    auc = roc_auc_score(y_test, y_proba)
    axes[0].plot(fpr, tpr, color=color, lw=2, label=f"{name} (AUC={auc:.3f})")
    
    # Precision-Recall curve
    precision, recall, _ = precision_recall_curve(y_test, y_proba)
    ap = average_precision_score(y_test, y_proba)
    axes[1].plot(recall, precision, color=color, lw=2, label=f"{name} (AP={ap:.3f})")

# ROC baseline
axes[0].plot([0, 1], [0, 1], 'k--', lw=1, label='Random baseline')
axes[0].set_xlabel("False Positive Rate (False Alarm Rate)")
axes[0].set_ylabel("True Positive Rate (Recall)")
axes[0].set_title("ROC Curves", fontweight='bold')
axes[0].legend()
axes[0].grid(alpha=0.3)

# PR baseline
baseline_pr = (y_test == 1).mean()
axes[1].axhline(y=baseline_pr, color='k', linestyle='--', lw=1, label=f'Random baseline ({baseline_pr:.2f})')
axes[1].set_xlabel("Recall (% of phishing caught)")
axes[1].set_ylabel("Precision (% of flagged that are real phishing)")
axes[1].set_title("Precision-Recall Curves\n(More meaningful for imbalanced data)", fontweight='bold')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

In [ ]:
# 8.4 — Summary comparison table: all models side by side

from sklearn.metrics import f1_score, precision_score, recall_score

summary_rows = []
for name, res in results.items():
    y_pred = res['y_pred']
    y_proba = res['y_proba']
    summary_rows.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision (phishing)': precision_score(y_test, y_pred),
        'Recall (phishing)': recall_score(y_test, y_pred),
        'F1 (phishing)': f1_score(y_test, y_pred),
        'ROC-AUC': roc_auc_score(y_test, y_proba),
        'Avg Precision (PR)': average_precision_score(y_test, y_proba),
    })

df_summary = pd.DataFrame(summary_rows).set_index('Model')

print("\n" + "="*75)
print("MODEL COMPARISON SUMMARY")
print("="*75)
print(df_summary.round(4).to_string())
print("="*75)

# Highlight winner per metric
print("\nBest model per metric:")
for col in df_summary.columns:
    best = df_summary[col].idxmax()
    val = df_summary[col].max()
    print(f"  {col:30s}: {best} ({val:.4f})")

In [ ]:
# 8.5 — Feature importance: what signals drive phishing predictions?

fig, axes = plt.subplots(1, 2, figsize=(18, 8))

# Logistic Regression: coefficients = feature weights
# Positive = pushes toward phishing, Negative = pushes toward legitimate
lr_coef = lr.coef_[0]
all_feature_names = list(tfidf.get_feature_names_out()) + HANDCRAFTED_COLS

# Top 20 positive (phishing) and negative (legitimate) features
top_n = 20
top_phishing_idx = lr_coef.argsort()[-top_n:][::-1]
top_legit_idx = lr_coef.argsort()[:top_n]

top_phishing_names = [all_feature_names[i] for i in top_phishing_idx]
top_phishing_coef = [lr_coef[i] for i in top_phishing_idx]

top_legit_names = [all_feature_names[i] for i in top_legit_idx]
top_legit_coef = [lr_coef[i] for i in top_legit_idx]

# Plot phishing-driving features
axes[0].barh(top_phishing_names[::-1], top_phishing_coef[::-1], color='#e74c3c')
axes[0].set_title("Top 20 Features → PHISHING\n(Logistic Regression coefficients)", fontweight='bold')
axes[0].set_xlabel("Coefficient (higher = stronger phishing signal)")
axes[0].axvline(x=0, color='black', linewidth=0.8)

# Plot legitimate-driving features
axes[1].barh(top_legit_names[::-1], [abs(c) for c in top_legit_coef[::-1]], color='#2ecc71')
axes[1].set_title("Top 20 Features → LEGITIMATE\n(Logistic Regression coefficients)", fontweight='bold')
axes[1].set_xlabel("|Coefficient| (higher = stronger legitimate signal)")

plt.suptitle("What makes the model predict phishing vs. legitimate?", 
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

## Summary & Next Steps

You now have a complete phishing detection pipeline:

1. **EDA** — Understood each dataset's shape, nulls, class distribution, and text length patterns
2. **Cleaning** — Unified 5 heterogeneous datasets into one clean DataFrame
3. **Preprocessing** — Standardized text (lowercase, remove HTML, replace URLs)
4. **Feature Engineering** — Combined TF-IDF vocabulary features with 9 handcrafted phishing-signal features
5. **Imbalance handling** — Used `class_weight='balanced'` / `scale_pos_weight`
6. **Training** — Trained 3 models: Logistic Regression, Random Forest, Gradient Boosting
7. **Evaluation** — Compared with Recall, Precision, F1, ROC-AUC, PR-AUC, confusion matrices

### How to choose the winner
- If **recall** is your priority (catch every phishing email, accept some false alarms): pick the model with highest recall on phishing class
- If **balance** matters (both catching phishing AND not annoying users): use F1-score as the tiebreaker
- For **deployment**, also consider: inference speed (LR is fastest), explainability (LR coefficients are readable), and memory (LR << RF << XGB)

### Potential improvements to explore
- **Threshold tuning**: models predict probabilities — you can lower the decision threshold from 0.5 to 0.3 to trade precision for recall
- **SMOTE**: synthetic oversampling of the minority class (alternative to class_weight)
- **Cross-validation**: use `StratifiedKFold` to get more robust metric estimates
- **More features**: sender domain spoofing patterns, HTML link count, reply-to mismatch
- **Fine-tuned BERT**: for the highest possible accuracy, a small distilBERT model trained on email text would outperform all of the above